version: '3.9'
services:
    app:
      container_name: joanna-api
      build:
           context: .
           dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - redis-net
    redis:
      container_name: redis-app
      image: docker.io/library/redis
      ports:
        - "6379:6379"
      networks:
        - redis-net

networks:
   redis-net:
